hotels/urls.py
from django.urls import path

from . import views

app_name = "hotels"

urlpatterns = [
    path("hotel", views.home, name="home"),
    path("hotels/<str:hotel_id>/", views.hotel_detail, name="hotel_detail"),
    path("search_hotel/", views.search_available_hotels, name="search_hotel"),
    path("hotels/<str:hotel_id>/search_room/", views.search_available_room, name="search_available_room"),
    path(
        "hotels/<int:hotel_id>/room/<int:room_id>/",
        views.room_detail,
        name="room_detail",
    ),
    path("hotels/book/<str:hotel_id>/", views.book_room, name="book_room"),
    path("booking/<str:booking_id>/", views.booking_detail, name="booking_detail"),
    path("view_voucher/", views.view_voucher, name="view_voucher"),
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("users.urls")), path("", include("tickets.urls")), path("", include("hotels.urls"))]

tickets/urls.py
from django.urls import path
from . import views

app_name = "tickets"

urlpatterns = [
    path("", views.home, name="home"),
    path("travel/", views.travel, name="travel"),
    path("search_travels/", views.search_travels, name="search_travels"),
    path("travels/<int:travel_id>/book/", views.book_ticket, name="book_travel"),
    path("vehicles/<int:vehicle_id>/", views.vehicle_detail, name="vehicle_detail"),
    path("ticket/<int:ticket_id>/", views.ticket_detail, name="ticket_detail"),
    
    path("travel/<int:travel_id>/", views.travel_detail, name="travel_detail"),
]

users/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("ticket/<str:ticket_id>/make_payment/", views.make_payment, name="make_payment"),
    path("booking/<str:booking_id>/make_payment/", views.make_payment_booking, name="make_payment_booking"),
    path("payment_success/<str:transaction_id>/", views.payment_success, name='payment_success'),
    # Other URL patterns
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),
    path('profile/', views.userProfile, name="user-profile"),
    path('edit-account/', views.editAccount, name="edit-account"),

    ##Experimental:
    path('tour_packages/', views.tour_packages, name='tour_packages'),
    path('discount/', views.discount, name='discount'),
    path('complain/', views.complain, name='complain'),

    ##Not included in Main
    path('profiles/', views.profiles, name="profiles"),
    path('account/', views.userAccount, name="account"),
    ## TODO
    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path('create-message/<str:pk>/', views.createMessage, name="create-message"),


]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" type="image/png" href="{% static 'images/favicon-32x32.png' %}">

    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <style>
      body {
        background:  #E0E9F0;
      }
    </style>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="{% url 'tickets:home' %}">Nemesis</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tickets:travel' %}">Travels</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'tickets:search_travels' %}">Search Travels</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hotels:home' %}">Hotels</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'hotels:search_hotel' %}">Search Hotels</a>
            </li>
          </ul>
          <ul class="navbar-nav">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:user-profile' %}">{{ user.username }}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Sign Out</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Login</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Sign Up</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
    
    
  {% block content %}{% endblock %}
    <!-- Bootstrap JS -->
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNVQ8ew"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    >
  </script>
  </body>
</html>