hotels/urls.py
from django.urls import path

from . import views

app_name = "hotels"

urlpatterns = [
    path("hotel", views.home, name="home"),
    path("hotels/<str:hotel_id>/", views.hotel_detail, name="hotel_detail"),
    path("search_hotel/", views.search_available_hotels, name="search_hotel"),
    path("hotels/<str:hotel_id>/search_room/", views.search_available_room, name="search_available_room"),
    path(
        "hotels/<int:hotel_id>/room/<int:room_id>/",
        views.room_detail,
        name="room_detail",
    ),
    path("hotels/book/<str:hotel_id>/", views.book_room, name="book_room"),
    path("booking/<str:booking_id>/", views.booking_detail, name="booking_detail"),
    path("view_voucher/", views.view_voucher, name="view_voucher"),
]

my_shop/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("users.urls")), path("", include("tickets.urls")), path("", include("hotels.urls"))]

tickets/urls.py
from django.urls import path
from . import views

app_name = "tickets"

urlpatterns = [
    path("", views.home, name="home"),
    path("travel/", views.travel, name="travel"),
    path("search_travels/", views.search_travels, name="search_travels"),
    path("travels/<int:travel_id>/book/", views.book_ticket, name="book_travel"),
    path("vehicles/<int:vehicle_id>/", views.vehicle_detail, name="vehicle_detail"),
    path("ticket/<int:ticket_id>/", views.ticket_detail, name="ticket_detail"),
    
    path("travel/<int:travel_id>/", views.travel_detail, name="travel_detail"),
]

users/urls.py
# urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path("ticket/<str:ticket_id>/make_payment/", views.make_payment, name="make_payment"),
    path("booking/<str:booking_id>/make_payment/", views.make_payment_booking, name="make_payment_booking"),
    path("payment_success/<str:transaction_id>/", views.payment_success, name='payment_success'),
    # Other URL patterns
    path('login/', views.loginUser, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('register/', views.registerUser, name="register"),
    path('profile/', views.userProfile, name="user-profile"),
    path('edit-account/', views.editAccount, name="edit-account"),

    ##Experimental:
    path('tour_packages/', views.tour_packages, name='tour_packages'),
    path('discount/', views.discount, name='discount'),
    path('complain/', views.complain, name='complain'),

    ##Not included in Main
    path('profiles/', views.profiles, name="profiles"),
    path('account/', views.userAccount, name="account"),
    ## TODO
    path('inbox/', views.inbox, name="inbox"),
    path('message/<str:pk>/', views.viewMessage, name="message"),
    path('create-message/<str:pk>/', views.createMessage, name="create-message"),


]

hotels/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid
from datetime import datetime, timedelta
from users.models import Payment
# Create your models here.


class Booking(models.Model):
    booking_id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    hotel = models.ForeignKey(
        "Hotel", on_delete=models.CASCADE, related_name="bookings_hotel"
    )
    room = models.ManyToManyField(
        "Room", related_name="bookings_room"
    )
    check_in_date = models.DateField()
    check_out_date = models.DateField()
    num_guests = models.PositiveIntegerField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    created = models.DateTimeField(auto_now_add=True)
    payment = models.ForeignKey(Payment,null=True,blank=True, on_delete=models.SET_NULL, related_name="payment_booking")

    def __str__(self):
        return f"{self.user.username}'s booking for hotel {self.hotel.hotel_name}"

    def book_room(self, room):
        if self.is_room_available(room):
            room.book(self.check_in_date, self.check_out_date)
            self.rooms.add(room)
            self.save()
            return True
        else:
            return False

    def calculate_overstay_charge(self):
        check_out = datetime.combine(self.check_out_date, datetime.min.time())
        actual_check_out = datetime.now()
        if actual_check_out > check_out:
            overstay_days = (actual_check_out - check_out).days
            overstay_charge = self.hotel.overstay_rate * overstay_days
            return overstay_charge
        else:
            return 0


class Hotel(models.Model):
    hotel_id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )
    HOTEL_TYPES = [
        ("budget", "Budget"),
        ("mid-range", "Mid-Range"),
        ("luxury", "Luxury"),
        ("resort", "Resort"),
    ]
    DHAKA = "Dhaka"
    CHITTAGONG = "Chittagong"
    SYLHET = "Sylhet"
    KHULNA = "Khulna"
    BARISAL = "Barisal"

    CITY_CHOICES = [
        (DHAKA, "Dhaka"),
        (CHITTAGONG, "Chittagong"),
        (SYLHET, "Sylhet"),
        (KHULNA, "Khulna"),
        (BARISAL, "Barisal"),
    ]
    hotel_type = models.CharField(max_length=50, choices=HOTEL_TYPES, default="budget")
    hotel_name = models.CharField(max_length=100)
    location = models.CharField(max_length=100, choices=CITY_CHOICES)
    overstay_rate = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.hotel_name


class Room(models.Model):
    room_id = models.UUIDField(
        default=uuid.uuid4, unique=True, primary_key=True, editable=False
    )
    ROOM_TYPES = [
        ("SINGLE", "Single"),
        ("DOUBLE", "Double"),
        ("TWIN", "Twin"),
        ("FAMILY", "Family"),
    ]
    room_number = models.CharField(max_length=10)
    hotel = models.ForeignKey(
        Hotel, on_delete=models.CASCADE, related_name="rooms_hotel"
    )
    room_type = models.CharField(max_length=50, choices=ROOM_TYPES)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    max_capacity = models.PositiveIntegerField()

    def __str__(self):
        return f"Room {self.room_number} at {self.hotel.hotel_name}"

    def is_available(self, check_in, check_out):
        bookings = Booking.objects.filter(hotel=self.hotel)
        for booking in bookings:
            if booking.check_in_date < check_out and booking.check_out_date > check_in:
                rooms = booking.rooms.all()
                if self in rooms:
                    return False
        return True

    def book(self, user, num_guests, check_in, check_out):
        availability = self.is_available(check_in, check_out)
        if availability:
            booking = Booking.objects.create(
                user=user,
                hotel=self.hotel,
                check_in_date=check_in,
                check_out_date=check_out,
                num_guests=num_guests,
                total_price=self.price,
            )
            booking.rooms.add(self)
            booking.save()
            return True
        else:
            return False

hotels/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Hotel, Room, Booking
from .forms import BookingForm, SearchHotelForm, RoomSearchForm
from django.db.models import Q
from django.db.models import Sum

def home(request):
    hotels = Hotel.objects.all()
    return render(request, "hotels/home.html", {"hotels": hotels})


def hotel_detail(request, hotel_id):
    hotel = get_object_or_404(Hotel, pk=hotel_id)
    # rooms = get_object_or_404(Room, hotel=hotel)
    rooms = Room.objects.filter(hotel=hotel)
    return render(request, "hotels/hotel_detail.html", {"hotel": hotel, "rooms": rooms})


def room_detail(request, hotel_id, room_id):
    hotel = get_object_or_404(Hotel, pk=hotel_id)
    room = get_object_or_404(Room, pk=room_id, hotel=hotel)
    return render(request, "hotels/room_detail.html", {"hotel": hotel, "room": room})


def search_available_hotels(request):
    if request.method == "POST":
        form = SearchHotelForm(request.POST)
        if form.is_valid():
            location = form.cleaned_data.get("location")
            hotel_type = form.cleaned_data.get("hotel_type", None)
            available_hotels = Hotel.objects.filter(
                location=location)
            if hotel_type: 
                available_hotels = available_hotels.filter(hotel_type=hotel_type).distinct()
            context = {
                "location": location,
                "hotels": available_hotels,
            }
            return render(request, "hotels/search_results.html", context)
    else:
        form = SearchHotelForm()

    context = {"form": form}
    return render(request, "hotels/search_hotels.html", context)

@login_required
def book_room(request, hotel_id):
    hotel = get_object_or_404(Hotel, pk=hotel_id)
    if request.method == "POST":
        form = BookingForm(hotel, request.POST)
        if form.is_valid():
            check_in_date = form.cleaned_data["check_in_date"]
            check_out_date = form.cleaned_data["check_out_date"]
            num_guests = form.cleaned_data["num_guests"]
            rooms = form.cleaned_data["room"]
            total_price = 0 
            for room in rooms:
                total_price += (
                    room.price * (check_out_date - check_in_date).days * num_guests
                )
            booking = Booking.objects.create(
                user=request.user,
                hotel=hotel,
                check_in_date=check_in_date,
                check_out_date=check_out_date,
                num_guests=num_guests,
                total_price=total_price,
            )
            booking.room.set(rooms)
            booking.save()
            messages.success(
                request,
                f"Room {room.room_number} at {hotel.hotel_name} has been booked successfully!",
            )
            return redirect("hotels:booking_detail", booking_id=booking.booking_id)
    else:
        form = BookingForm(hotel)
    return render(request, "hotels/book_room.html", {"hotel": hotel, "form": form})



def booking_detail(request, booking_id):
    booking = get_object_or_404(Booking, pk=booking_id)
    overstay_charge = booking.calculate_overstay_charge()
    return render(
        request,
        "hotels/booking_detail.html",
        {"booking": booking, "overstay_charge": overstay_charge},
    )


def search_available_room(request, hotel_id):
    hotel = Hotel.objects.get(hotel_id=hotel_id)
    if request.method == 'POST':
        form = RoomSearchForm(request.POST)
        if form.is_valid():
            room_type = form.cleaned_data['room_type']
            check_in = form.cleaned_data['check_in']
            check_out = form.cleaned_data['check_out']
            available_rooms = Room.objects.filter(hotel=hotel, room_type=room_type, max_capacity__gte=form.cleaned_data['num_guests'])
            for room in available_rooms:
                if not room.is_available(check_in, check_out):
                    available_rooms = available_rooms.exclude(room_id=room.room_id)
            return render(request, 'hotels/available_rooms.html', {'hotel': hotel, 'available_rooms': available_rooms})
    else:
        form = RoomSearchForm(hotel_id)
    return render(request, 'hotels/room_search.html', {'form': form})

def view_voucher(request):
#     ver_dict = {

#   "check_in": "2:00 PM, Saturday, 30 Sep, 2023",
#   "check_out": "12:00 PM, Sunday, 01 Oct, 2023",
#   "hotel_fax": "N/A",
#   "hotel_name": "Hotel Sarina",
#   "rate_class": "Refundable",
#   "vat_number": "",
#   "addons_list": [],
#   "hotel_email": "N/A",
#   "hotel_image": "http://photos.hotelbeds.com/giata/original/41/411038/411038a_hb_a_010.jpg",
#   "hotel_phone": "N/A",
#   "gz_reference": "HB2204030001",
#   "hotel_rating": "5",
#   "hotel_address": "Plot #27, Road #17, Banani C/A, Dhaka 1213, Banani, 4, BD",
#   "optional_fees": "Coke Tk40",
#   "supplier_name": "Hotelbeds",
#   "mandatory_fees": "Breakfast Tk50",
#   "payable_amount": "BDT 15,193",
#   "hotel_reference": "448-4988",
#   "primary_contact": "tanvir palash",
#   "is_expedia_hotel": False,
#   "reservation_date": "Sun, 03 Apr, 2022",
#   "is_gozayaan_hotel": True,
#   "room_cancel_policy": [
#     {
#       "room_name": "DOUBLE DELUXE",
#       "room_policy": {
#         "1": [
#           "Free cancellation upto YYYY-MM-DD.",
#           "Cancellation charge BDT 4000 from YYYY-MM-DD."
#         ]
#       }
#     },
#     {
#       "room_name": "DOUBLE DELUXE",
#       "room_policy": {
#         "1": [
#           "Free cancellation upto YYYY-MM-DD.",
#           "Cancellation charge BDT 4000 from YYYY-MM-DD."
#         ]
#       }
#     },
#     {
#       "room_name": "DOUBLE DELUXE",
#       "room_policy": {
#         "1": [
#           "Free cancellation upto YYYY-MM-DD.",
#           "Cancellation charge BDT 4000 from YYYY-MM-DD."
#         ]
#       }
#     },
#     {
#       "room_name": "DOUBLE DELUXE",
#       "room_policy": {
#         "1": [
#           "Free cancellation upto YYYY-MM-DD.",
#           "Cancellation charge BDT 4000 from YYYY-MM-DD."
#         ]
#       }
#     }
#   ],
#   "room_voucher_details": [
#     {
#       "adult": "1",
#       "board": "Bed and breakfast",
#       "child": "2 (Age 5, Age 7)",
#       "remarks": " .  Check-in hour -12:00.Car park YES (with additional debit notes).Due to the pandemic, many accommodation and service providers may implement processes and policies to help protect the safety of all of us. This may result in the unavailability or changes in certain services and amenities that are normally available from them. More info here https://cutt.ly/MT8BJcv (15/05/2020-30/06/2022) ",
#       "included": [
#         "Free WIFI",
#         "Breakfast"
#       ],
#       "room_name": "DOUBLE DELUXE",
#       "customer_name": "tanvir palash"
#     }
#   ],
#   "check_in_instructions": "Just check in",
#   "check_out_instructions": "Just check out",
#     "hotel_booking_id": "HB2204030001",
#       "nights": 2,
#                   "primary_contact_phone": "primary_contact_phone",
#             "primary_contact_email": "primary_contact_email",
# "room_details": [
#     {
#         "room_name": "Junior Suite Sea View",
#         "paxes": [
#             {
#                 "name": "Mesba Ul Azim",
#                 "type": "AD"
#             }, 
#             {
#                 "name": "Tasfia Khan", 
#                 "type": "CH"
#             }
#         ],
#         "plan": "Bed & Breakfast (Non-Refundable)"
#     },
#     {
#         "room_name": "Junior Suite View",
#         "paxes": [
#             {
#                 "name": "Ibrahim Imran",
#                 "type": "AD"
#             }, 
#             {
#                 "name": "Laily Akhter", 
#                 "type": "CH"
#             }
#         ],
#         "plan": "Bed & Breakfast (Refundable)"
#     },
#     {
#         "room_name": "Suite Sea View",
#         "paxes": [
#             {
#                 "name": "Mesbzim",
#                 "type": "AD"
#             }, 
#             {
#                 "name": "Tasfhan", 
#                 "type": "AD"
#             }
#         ],
#         "plan": "Bed & Breakfast (Refundable)"
#     },
#     {
#         "room_name": "Junior Suite Sea",
#         "paxes": [
#             {
#                 "name": "Azim",
#                 "type": "AD"
#             }, 
#             {
#                 "name": "Khan", 
#                 "type": "AD"
#             }
#         ],
#         "plan": "Bed & Breakfast (Refundable)"
#     }
# ],
#             "pet_policy": "Not Allowed",
#                         "house_rules": "house_rules",
#                         "is_bd_region": True,
#                         "is_expedia_hotel": True,
#                         "check_in_instruction": "Pay Hotel boy 500 taka",
#                         "mandatory_fees": "505.50",
#                         "child_policy": "Only year 5 Allowed",
#                         "map_hotel":"https://maps.app.goo.gl/YrpxNppK3rZ3ATGC9"
# }
    ver_dict={
        'name': "Tahseen Zaman",
        'booking_id': "123456",
        'region': "BD",
        'amount': 'BDT 1,500.00',
            }
    return render(
        request,
        "hotels/payment-confirmation-v2.html",
        ver_dict,
    )

templates/hotels/availavle_room.html
{% extends 'base.html' %}

{% block content %}
  <h1>Available Rooms at {{ hotel.hotel_name }}</h1>
  <p><strong>Location:</strong> {{ hotel.location }}</p>
  
  <form method="GET" class="form-inline my-3">
    <div class="form-group mr-2">
      <label for="room_type">Room Type:</label>
      {{ form.room_type }}
    </div>
    <button type="submit" class="btn btn-primary">Search</button>
  </form>
  
  {% if rooms %}
    <p>{{ rooms.count }} room(s) found.</p>
    <table class="table">
      <thead>
        <tr>
          <th>Room Number</th>
          <th>Room Type</th>
          <th>Price</th>
          <th>Max Capacity</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for room in rooms %}
          <tr>
            <td>{{ room.room_number }}</td>
            <td>{{ room.get_room_type_display }}</td>
            <td>{{ room.price }}</td>
            <td>{{ room.max_capacity }}</td>
            <td>
              <a href="{% url 'hotels:book_room' room_id=room.room_id %}" class="btn btn-primary">
                Book Now
              </a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>No rooms available.</p>
  {% endif %}
{% endblock %}

templates/hotels/booking_detail.html
{% extends 'base.html' %}

{% block content %}
{% load static%}
  <div class="container my-5">
    <div class="row">
      <div class="col-md-6">
        <div class="card">
          <div class="card-header">
            <strong>Booking Details:</strong>
          </div>
          <div class="card-body">
            <table class="table table-bordered table-striped">
              <thead>
                <tr>
                  <th>Booking Number</th>
                  <th>{{ booking.booking_id }}</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>Rooms:</td>
                  <td><p> 
                      {% for room in booking.room.all %}
                         Room - {{ room.room_number }}{% if not forloop.last %}, {% endif %}
                      {% endfor %}
                      </p></td>
                </tr>
                <tr>
                  <td>Check in Date:</td>
                  <td>{{ booking.check_in_date }}</td>
                </tr>
                <tr>
                  <td>Check out Date:</td>
                  <td>{{ booking.check_out_date }}</td>
                </tr>
                <tr>
                  <td>Total Price:</td>
                  <td>{{ booking.total_price }}</td>
                </tr>
                <tr>
                  <td>Created on:</td>
                  <td>{{ booking.created }}</td>
                </tr>
                <tr>
                  <td>Payment for the Booking:</td>
                  <td><strong>{{ booking.payment.status }}</strong></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h2>Contact Information</h2>
        <hr>
        <p><strong>Name:</strong> {{ booking.user.username }}</p>
        <p><strong>Email:</strong> {{ booking.user.email }}</p>
        <p><strong>Phone:</strong> {{ booking.user.profile.phone_number }}</p>
        <p><strong>Address:</strong> {{ booking.user.profile.address }}</p>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center align-items-center">
    <a href="{% url 'users:make_payment_booking' booking.booking_id %}" class="btn btn-lg btn-primary">Make Payment</a>
  </div> 
  </br>
  <div class="container">
    <section
      class="jumbotron jumbotron-fluid"
      style="
        background-image: url('{% static 'images/011.jpg' %}');
        background-size: cover;
        background-position: center;
      "
    >
      <div class="container">
        <h1 class="display-1">Nemesis</h1>
        <p class="display-4">Where Adventure Meets Accommodation</p>
        <p class="lead">
          Welcome! Please select a vehicle and choose your preferred seat on the
          next page
        </p>
        <p class="lead">
          Some vehicles may have different seating sections or classes, so choose
          the appropriate section if applicable
        </p>
        <p><strong>Please Explore more:</strong></p>
        <a href="{% url 'tickets:search_travels' %}" class="btn btn-lg btn-primary"
          >Search a Ticket</a
        >
      </div>
    </section>
    </div> 
{% endblock %}

templates/hotels/home.html
{% extends 'base.html' %} {% block content %} {% load static %}

<div class="container d-flex justify-content-center align-items-center">
  <section id="showcase">
    <h2 class="display-4">Let's make a home far from house</h2>
    <div id="carousel" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carousel" data-slide-to="0" class="active"></li>
        <li data-target="#carousel" data-slide-to="1"></li>
        <li data-target="#carousel" data-slide-to="2"></li>
        <li data-target="#carousel" data-slide-to="3"></li>
      </ol>
      <div class="carousel-inner" role="listbox" style="text-align: center">
        <div class="carousel-item active">
          <img
            src="{% static 'images/010.jpg'%}"
            alt="Slide #1"
            class="d-block img-fluid"
          />
          <div class="carousel-caption">
            <h3 class="display-4">US Bangla</h3>
            <p>
              Our Partnership with US Bangla gets you the most affordable rate
            </p>
          </div>
        </div>
        <div class="carousel-item">
          <img
            src="{% static 'images/006.jpg'%}"
            alt="Slide #2"
            class="d-block img-fluid"
          />
          <div class="carousel-caption">
            <h3 class="display-4">Bangladesh Railways</h3>
            <p>Look no further when booking Railways!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img
            src="{% static 'images/007.jpg'%}"
            alt="Slide #3"
            class="d-block img-fluid"
          />
          <div class="carousel-caption">
            <h3 class="display-4">Travel Anywhere</h3>
            <p>Explore the wonders</p>
          </div>
        </div>
        <div class="carousel-item">
          <img
            src="{% static 'images/009.jpg'%}"
            alt="Slide #4"
            class="d-block img-fluid"
          />
          <div class="carousel-caption">
            <h3 class="display-4">In the distance</h3>
            <p>
              A place where you can see the best of nature with a relaxing and
              luxurious stay.
            </p>
          </div>
        </div>
      </div>
      <a
        href="#carousel"
        class="carousel-control-prev"
        role="button"
        data-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a
        href="#carousel"
        class="carousel-control-next"
        role="button"
        data-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </section>
</div>
<div class="container">
  <section
    class="jumbotron jumbotron-fluid"
    style="
      background-image: url('{% static 'images/015.jpg' %}');
      background-size: cover;
      background-position: center;
    "
  >
  <div class="container d-flex justify-content-center align-items-center">
    <div class="row">
      <div class="col-md-12">
      <h1>Welcome to our Hotel Booking</h1>
      <p>Choose a Hotel to start booking your Room:</p>
      <div class="row">
        {% for hotel in hotels %}
        <div class="col-md-4 mb-3">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">
                A {{ hotel.hotel_type }} hotel at {{ hotel.location }}
              </h5>
              <p class="card-text">Name: {{ hotel.hotel_name }}</p>
              <a
                href="{% url 'hotels:hotel_detail' hotel_id=hotel.hotel_id %}"
                class="btn btn-primary"
                >Show details of the Hotel</a
              >
            </div>
          </div>
        </div>
        {% empty %}
        <p>There are no Hotel available.</p>
        {% endfor %}
      </div>
    </div>
  </section>
</div>
<div class="container">
  <section
    class="jumbotron jumbotron-fluid"
    style="
      background-image: url('{% static 'images/011.jpg' %}');
      background-size: cover;
      background-position: center;
    "
  >
    <div class="container">
      <h1 class="display-1">Nemesis</h1>
      <p class="display-4">Where Adventure Meets Accommodation</p>
      <p class="lead">
        Welcome! Please select a Hotel and choose your preferred Rooms on the
        next page
      </p>
      <p class="lead">
        Some hotels may have different Booking service sections or classes, so choose
        the appropriate section if applicable
      </p>
      <p><strong>Please Explore more:</strong></p>
      <a href="{% url 'hotels:search_hotel' %}" class="btn btn-lg btn-primary"
        >Search a Hotel</a
      >
    </div>
  </section>
  </div>

{% endblock %}

templates/hotels/search_results.html
{% extends 'base.html' %} {% block content %}
{%load static%}
<div class="container d-flex justify-content-center align-items-center">
  {% if hotels %}
  <div class="align-items-center col-12">
    <h1>Available Hotels in {{ location }} :</h1>
    <ul>
      {% for hotel in hotels %}
      <li>
        {{ hotel.hotel_type }} hotel in {{ hotel.location }}:
        <a
          href="{% url 'hotels:hotel_detail' hotel_id=hotel.hotel_id %}"
          class="btn btn-primary"
          >{{ hotel.hotel_name }}</a
        >
      </li>
      {% endfor %}
    </ul>
    {% else %}
    <div class="col-6">
      <h1>No available hotels found in {{ location }}</h1>
    </div>
    {% endif %}
  </div>
</div>
<div class="container d-flex justify-content-center align-items-center">
  <section id="section-pricing">
    <h2 class="display-4 text-center">Hot Deals</h2>
    <div class="row">
      <div class="col-12 col-md-4 mb-4">
        <div class="card card-outline-light">
          <div class="card-header text-dark text-center">
            <h2>On Flight Bookings</h2>
            <h4>15% Discount</h4>
          </div>
          <div class="card-body">
            <p class="card-text">For US Bangla Airline ticket booking</p>
          </div>
          <ul class="list-group">
            <li class="list-group-item">
              <i class="fa fa-fw fa-paint-brush" aria-hidden="true"></i> On base
              fare, for bKash payment.
            </li>
            <li class="list-group-item">
              <i class="fa fa-fw fa-instagram" aria-hidden="true"></i> Till 30
              Jun’23.
            </li>
          </ul>
        </div>
      </div>
      <div class="col-12 col-md-4 mb-4">
        <div class="card card-outline-light">
          <div class="card-header text-dark text-center">
            <h2>On Domestic Hotel Bookings for bKash</h2>
            <h4>10% Discount</h4>
          </div>
          <ul class="list-group">
            <li class="list-group-item">
              <i class="fa fa-fw fa-paint-brush" aria-hidden="true"></i> Till 30
              Jun '23.
            </li>
          </ul>
        </div>
      </div>
      <div class="col-12 col-md-4 mb-4">
        <div class="card card-outline-light">
          <div class="card-header text-dark text-center">
            <h2>On Int’l Flight Bookings</h2>
            <h4>Upto 2,000 taka off</h4>
          </div>
          <ul class="list-group">
            <li class="list-group-item">
              <i class="fa fa-fw fa-paint-brush" aria-hidden="true"></i> On base
              fare, for City Bank American Express® Platinum & Gold credit
              cards. Till 31 Dec’23
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
</div>
<div class="container">
  <section
    class="jumbotron jumbotron-fluid"
    style="
      background-image: url('{% static 'images/011.jpg' %}');
      background-size: cover;
      background-position: center;
    "
  >
    <div class="container">
      <h1 class="display-1">Nemesis</h1>
      <p class="display-4">Where Adventure Meets Accommodation</p>
      <p class="lead">
        Welcome! Please select a vehicle and choose your preferred seat on the
        next page
      </p>
      <p class="lead">
        Some vehicles may have different seating sections or classes, so choose
        the appropriate section if applicable
      </p>
      <p><strong>Please Explore more:</strong></p>
      <a href="{% url 'tickets:search_travels' %}" class="btn btn-lg btn-primary"
        >Search a Ticket</a
      >
    </div>
{% endblock %}